name: Build and Deploy WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to your branch as necessary
      - gh-pages
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build WebAssembly
      run: |
            chmod +x ./build-for-web.sh && ./build-for-web.sh ndarray

    - name: Prepare Files for Deployment
      run: |
        mkdir web-publish
        cp -r inference.js web-publish/
        cp -r inference_bg.wasm web-publish/
        cp index.html web-publish/
        cp index.js web-publish/
        cp -r models web-publish/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./web-publish
